### ISSUE TITLE
All documentation has "_" as a prefix: This prevents typedocs from being served in gh-pages.

### ISSUE THREAD

**Issue by electricessence** [sebastian-lenz/typedoc#149]
After removing the "_" in front of all my documentation files, gh-pages worked.

**Comment by sebastian-lenz** [comment]
I've noted that too, but this a specific behaviour of GitHub pages and can be easily fixed by including a <code>.nojekyll</code> file at the document root. Documentation on this can be found [here](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/).

The underscores are created by the url builder when hitting external modules. There are issues describing better solutions and it should be gone in v0.4.

**Comment by electricessence** [comment]
Ok, so would you say that adding the .nojekyll is better?

**Comment by cope** [comment]
@vsund How long after adding that did you see it working? :(

**Comment by aciccarello** [comment]
@cope Shouldn't be too long. Within a half hour.

**Comment by cope** [comment]
@vsund tnx, it turned out it was still my mistake, I had two _config.yml files and I was editing the wrong one... once I fixed the right one it was available immediately

**Comment by DanielRuf** [comment]
This is still not fixed - and it seems it worked in the past but doesn't anymore.

**Comment by SgtPooki** [comment]
404 errors are still occuring at ipfs.github.io/helia (source at https://github.com/ipfs/helia/tree/f84b0155ce3f8c37955e51c26047d94906b44aa9)

If you click into a module, and then click the header, you get sent to https://ipfs.github.io/helia/modules/ which is a 404, because there is no index.html there.
